---

- name: Install Homebrew and packages

  hosts: all

  vars_files:
    - config.default.yml

  pre_tasks:
    - name: Test Connection
      ping:

  roles:
    - role: "homebrew"
      tags: ['homebrew']
